
```{r}
### For now, let's just make up some data for the purposes of method development
### this will need to go into test code too
set.seed(9873)
loso_pred_res <- data.frame(
  model = paste0("log_score_", rep(letters[1:3], each = 100)),
  d = rep(1:100, times = 3),
  loso_log_score = c(
    log(runif(100, 0, 1)), # model a's performance not related to d
    sort(log(runif(100, 0, 1))), # model b's performance increasing in d
    rep(-0.5, 100))  # model c's performance constant
) %>%
  spread(model, loso_log_score)

# ggplot(loso_pred_res) + geom_point(aes(x = d, y = loso_log_score, colour = model, group = model))

## convert training data to format used in xgboost
## refactor this into part of fit method eventually
component_models <- letters[1:3]
predictive_vars <- "d"
dtrain <- xgb.DMatrix(
  data = as.matrix(loso_pred_res[, predictive_vars, drop = FALSE]) %>%
    `storage.mode<-`("double"))

## xgb.DMatrix enforces certain dimensions and data types for the "info"
## argument, which is what could otherwise be used to encode the log scores for
## each component model.  Instead, we'll have to resort to storing them in a
## suitable environment and then pulling them out of that environment
## within the custom objective function.
storage_env <- new.env(parent = .GlobalEnv) # long term, where should storage_env live?  not in .GlobalEnv, that's illegal...
assign("num_models",
  length(component_models),
  envir = storage_env)
assign("component_log_scores",
  as.matrix(
    loso_pred_res[, paste0("log_score_", component_models), drop = FALSE]
  ) %>%
  `storage.mode<-`("double"),
  envir = storage_env)
```


```{r}
### call xbg.train to do estimation.
### refactor this to be part of fit method eventually.
debug(test_obj)
fit <- xgb.train(
  params = list(
    booster = "gbtree", # change to gblinear to fit lines
    subsample = 0.5, # use half of the observations in each boosting iteration
    colsample_bytree = 1, # use all of the columns to do prediction (for now, only one column...)
    num_class = length(component_models)
  ),
  data = dtrain,
  nrounds = 100,
  obj = test_obj
)

```
